version: "3"

services:

    shopware:
      container_name: shopware5
      image: dockware/dev:5.6.9
      ports:
         - "80:80"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1

networks:
  web:
    external: false