version: "3"

services:

    shopware:
      container_name: shopware5
      image: dockware/dev:5.6.9
      ports:
         - "80:80"
      networks:
         - web
      volumes:
        - ./custom:/var/www/html/custom
        - ./themes:/var/www/html/themes
        - ./engine:/var/www/html/engine:ro
        - ./config.php:/var/www/html/config.php:ro
      environment:
         - XDEBUG_ENABLED=1

networks:
  web:
    external: false